(evil-global-set-key 'normal (kbd "n") 'evil-next-respect-isearch)
(evil-global-set-key 'normal (kbd "N") 'evil-previous-respect-isearch)
(with-eval-after-load 'evil-evilified-state (define-key evil-evilified-state-map-original (kbd "N") 'evil-previous-respect-isearch)
                      (define-key evil-evilified-state-map-original (kbd "n") 'evil-next-respect-isearch)
                      )
(with-eval-after-load 'evil-states (define-key evil-motion-state-map (kbd "n") 'evil-next-respect-isearch)
                      (define-key evil-motion-state-map (kbd "N") 'evil-previous-respect-isearch)
                      )
(add-hook 'dired-mode-hook '(lambda ()
                              (evil-define-key 'normal dired-mode-map (kbd "n") 'evil-next-respect-isearch)
                              (evil-define-key 'normal dired-mode-map (kbd "N") 'evil-previous-respect-isearch)
                              ))
