(global-set-key (kbd "C-M-]") 'company-complete)
(evil-global-set-key 'normal (kbd "\C-cl") 'org-store-link)
(evil-global-set-key 'normal (kbd "C-M-n") 'evil-jump-forward)
(evil-global-set-key 'normal (kbd "n") 'evil-next-respect-isearch)
(evil-global-set-key 'normal (kbd "N") 'evil-previous-respect-isearch)
(evil-global-set-key 'normal (kbd ">") 'goto-delimiter-forward)
(evil-global-set-key 'visual (kbd ">") 'goto-delimiter-forward)
(evil-global-set-key 'operator (kbd ">") 'goto-delimiter-forward)
(evil-global-set-key 'normal (kbd "H") 'goto-delimiter-backward-stop)
(evil-global-set-key 'visual (kbd "H") 'goto-delimiter-backward-stop)
(evil-global-set-key 'operator (kbd "H") 'goto-delimiter-backward-stop)
(evil-global-set-key 'normal (kbd "<") 'goto-delimiter-backward)
(evil-global-set-key 'visual (kbd "<") 'goto-delimiter-backward)
(evil-global-set-key 'operator (kbd "<") 'goto-delimiter-backward)
(evil-global-set-key 'visual (kbd "{") '(lambda nil (interactive)
                                          (progn (call-interactively (quote evil-shift-left)) (execute-kbd-macro "gv"))))
(evil-global-set-key 'visual (kbd "}") '(lambda nil (interactive)
                                          (progn (call-interactively (quote evil-shift-right)) (execute-kbd-macro "gv"))))
(global-set-key (kbd "M-h") 'backward-delete-char)
(evil-define-key 'normal evil-matchit-mode-map
  "M" 'evilmi-jump-items)
(evil-define-key 'visual evil-matchit-mode-map
  "M" 'evilmi-jump-items)
(evil-define-key 'operator evil-matchit-mode-map
  "M" 'evilmi-jump-items)
(spacemacs/set-leader-keys "ec" 'eshell-copy-last-command-output)
(spacemacs/set-leader-keys "o" 'helm-multi-swoop-org)
(spacemacs/set-leader-keys "sgp" 'helm-projectile-rg)
(spacemacs/set-leader-keys "r/" 'helm-rg)
(spacemacs/set-leader-keys "zp" 'zeal-at-point)
(spacemacs/set-leader-keys "io" 'org-insert-heading)
(spacemacs/set-leader-keys ":" 'eval-expression)
(spacemacs/set-leader-keys "ee" 'switch-to-eshell)
(spacemacs/set-leader-keys "ys" 'describe-variable-and-kill-value)
(spacemacs/set-leader-keys "." 'ido-switch-buffer)

(global-set-key (kbd "M-l") 'custom-layout1)
(global-set-key (kbd "\C-xb") 'ido-switch-buffer)
(global-set-key (kbd "\C-x\C-f") 'ido-find-file)
(global-set-key (kbd "\C-x.") 'helm-eshell-history)
(global-set-key (kbd "\C-x.") 'helm-eshell-history)
(global-set-key (kbd "\C-x/") 'helm-complex-command-history)
(global-set-key (kbd "\C-x,") 'command-history)
(global-set-key (kbd "\C-x]") 'ace-window)


